# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='type_place',
            field=models.CharField(choices=[('a', 'Apartment'), ('h', 'House'), ('w', 'Warehouse'), ('b', 'Basement')], max_length=1, verbose_name='Type of Place'),
        ),
    ]
