# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 00:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date', models.DateField()),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Contracts',
                'verbose_name': 'Contract',
            },
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('section8_amount', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Section 8 Amount')),
                ('tenant_amount_due', models.DecimalField(decimal_places=2, max_digits=5)),
                ('security_deposit_due', models.DecimalField(decimal_places=2, max_digits=5)),
                ('misc_add_fees', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Miscellaneous Aditional Fees')),
                ('backrent_amount_due', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tenant_total_amount_due', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_paid', models.DecimalField(decimal_places=2, max_digits=5)),
                ('month_balance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rents.Contract')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.Place')),
            ],
            options={
                'verbose_name_plural': 'Rents',
                'verbose_name': 'Rent',
            },
        ),
        migrations.CreateModel(
            name='RentDeduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('payment', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rents.Rent')),
            ],
            options={
                'verbose_name_plural': 'RentDeductions',
                'verbose_name': 'RentDeduction',
            },
        ),
    ]
