# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 00:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rents', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rent',
            old_name='security_deposit_due',
            new_name='sec_deposit_due',
        ),
    ]
