# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rents', '0002_auto_20161119_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='backrent_amount_due',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='rent',
            name='misc_add_fees',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Miscellaneous Aditional Fees'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='month_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='rent',
            name='sec_deposit_due',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Security Deposit Due'),
        ),
    ]
